import { expect, test } from "vitest";
import { buildRound } from "@/lib/round-builder";
import { isCorrect, scoreGuesses } from "@/lib/scoring";
import { sessionSchema, guessSchema, nicknameSchema } from "@/lib/schemas";
const pairs = Array.from({length:15},(_,i)=>({id:String(i),category:"science",is_active:true,is_attention_check:false}));
test("paired rounds are unique, bounded, and accommodate scarcity",()=>{const r=buildRound(pairs,[],"paired");expect(r).toHaveLength(9);expect(new Set(r.map(i=>i.pairId)).size).toBe(9);expect(buildRound(pairs.slice(0,2),[],"paired")).toHaveLength(2);expect(buildRound([],[],"paired")).toEqual([]);});
test("server layout determines correctness and streaks",()=>{expect(isCorrect("paired",{fake_shown_on:"left",shown_answer:null},{chosenSide:"left"})).toBe(true);expect(isCorrect("paired",{fake_shown_on:"right",shown_answer:null},{chosenSide:"left"})).toBe(false);expect(scoreGuesses([true,true,false,true].map(is_correct=>({is_correct})))).toEqual({score:3,currentStreak:1,bestStreak:2});});
test("nickname validation",()=>{for(const name of ["Fact Finder","a_2-x"])expect(nicknameSchema.safeParse(name).success).toBe(true);for(const name of ["a","x".repeat(21),"<script>","fuck","   "])expect(nicknameSchema.safeParse(name).success).toBe(false);});
test("schemas require consent and reject scores and malformed choices",()=>{expect(sessionSchema.safeParse({consent:true,ageConfirmed:true}).success).toBe(true);for(const value of [{consent:false,ageConfirmed:true},{consent:true},{consent:true,ageConfirmed:true,condition:"paired"}])expect(sessionSchema.safeParse(value).success).toBe(false);const g={sessionId:"00000000-0000-4000-8000-000000000001",position:1,chosenSide:"left",confidence:3,responseTimeMs:2000};expect(guessSchema.safeParse(g).success).toBe(true);for(const extra of [{confidence:6},{score:10},{judgment:"yes"},{position:0},{sessionId:"bad"}])expect(guessSchema.safeParse({...g,...extra}).success).toBe(false);});
