"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CheckCircle2, Flame, ShieldCheck, XCircle } from "lucide-react";
import { api } from "@/lib/client-api";
import type { PublicItem, Reveal, SessionInfo, Side, Summary } from "@/lib/types";

export function PlayGame() {
 const [session, setSession] = useState<SessionInfo | null>(null);
 const [item, setItem] = useState<PublicItem | null>(null);
 const [summary, setSummary] = useState<Summary | null>(null);
 const [streak, setStreak] = useState(0);
 const [busy, setBusy] = useState(false);
 const [error, setError] = useState("");
 async function start(data: { nickname?: string }) { setBusy(true); setError(""); try { const s = await api<SessionInfo>("/api/sessions", { consent:true, ageConfirmed:true, ...data, deviceType:window.innerWidth < 768 ? "mobile" : "desktop" }); setSession(s); setItem(await api<PublicItem>(`/api/sessions/${s.sessionId}/items/1`)); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
 async function next() { if (!session || !item) return; setBusy(true); setError(""); try { if (item.position === session.totalItems) setSummary(await api<Summary>(`/api/sessions/${session.sessionId}/complete`,{})); else setItem(await api<PublicItem>(`/api/sessions/${session.sessionId}/items/${item.position + 1}`)); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
 return <div className="play-shell">{error && <p className="error" role="alert">{error}</p>}{summary ? <section className="end-screen"><span className="icon-orbit"><Check aria-hidden="true" /></span><p className="eyebrow">Round complete</p><h1>Good eye, human.</h1><p className="score">{summary.score}<span> / {summary.total}</span></p><p>Best streak: {summary.bestStreak}</p><a className="button primary" href="/play">Play again <ArrowRight aria-hidden="true" /></a><Link href="/leaderboard">View leaderboard</Link></section> : item && session ? <GameItem key={item.position} item={item} session={session} streak={streak} next={next} busy={busy} onReveal={r => setStreak(r.currentStreak)} /> : <Consent start={start} busy={busy} />}</div>;
}
function Consent({start,busy}:{start:(data:{nickname?:string})=>Promise<void>;busy:boolean}) {
 const [age,setAge] = useState(false), [consent,setConsent] = useState(false), [nickname,setNickname] = useState("");
 return <section className="narrow"><p className="eyebrow">Before the hunt</p><h1>A little game.<br />A real study.</h1><p className="lede">Your eye for detail can help us understand how people spot AI hallucinations.</p><div className="panel consent-copy"><ShieldCheck aria-hidden="true" /><div><h2>You’re in control</h2><p>This is an anonymous research study. Participation is voluntary. We collect no names or emails. Your guesses are stored anonymously, and anonymized data may be published.</p><p>You can stop at any time by closing this tab. Read our <Link href="/privacy">privacy details</Link>.</p></div></div><form onSubmit={e => { e.preventDefault(); if (age && consent && !busy) void start(nickname.trim() ? {nickname:nickname.trim()} : {}); }}><label className="field">Nickname <span className="muted">optional · for the leaderboard</span><input value={nickname} onChange={e => setNickname(e.target.value)} minLength={2} maxLength={20} pattern="[A-Za-z0-9 _\-]+" placeholder="e.g. Fact Detective" autoComplete="off" /><span className="muted small">Use a made-up alias, never your real name. Letters, numbers, spaces, _ or -.</span></label><label className="checkbox"><input type="checkbox" checked={age} onChange={e=>setAge(e.target.checked)} required /> I am 18 or older</label><label className="checkbox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required /> I agree to take part</label><button className="button primary full" disabled={!age || !consent || busy}>{busy ? "Preparing your round…" : "Start the hunt"}<ArrowRight aria-hidden="true" /></button></form></section>;
}
function GameItem({item,session,streak,next,busy,onReveal}:{item:PublicItem;session:SessionInfo;streak:number;next:()=>Promise<void>;busy:boolean;onReveal:(r:Reveal)=>void}) {
 const started = useRef(0), elapsed = useRef(0), submitting = useRef(false);
 const [choice,setChoice] = useState<Side | null>(null), [reveal,setReveal] = useState<Reveal | null>(null), [sending,setSending] = useState(false), [error,setError] = useState("");
 useEffect(()=>{ const frame = requestAnimationFrame(()=>{started.current = performance.now();}); return ()=>cancelAnimationFrame(frame); },[]);
 function handleChoose(side:Side, clickedAt:number) { if (choice || reveal) return; elapsed.current = Math.round(clickedAt - (started.current || clickedAt)); setChoice(side); }
 async function submit(confidence:number) { if (!choice || submitting.current || reveal) return; submitting.current=true;setSending(true);setError(""); try { const r = await api<Reveal>("/api/guesses",{sessionId:session.sessionId,position:item.position,chosenSide:choice,confidence,responseTimeMs:elapsed.current});setReveal(r);onReveal(r); } catch(e) {setError((e as Error).message);} finally {submitting.current=false;setSending(false);} }
 const index = reveal?.fabricatedAnswer.indexOf(reveal.fabricatedSpan) ?? -1;
 return <section><div className="round-top"><span className="eyebrow">The hunt <span className="muted">/</span> {item.position} / {item.totalItems}</span><span className="streak"><Flame size={16} aria-hidden="true" />{streak} streak</span></div><progress value={item.position} max={item.totalItems} aria-label="Round progress" /><div className="question-block"><p className="eyebrow">{item.category}</p><h1>{item.question}</h1><p className="muted">One answer contains a fabricated fact. Which one?</p></div>{"left" in item.display && <div className="answers">{(["left","right"] as const).map((side,i)=><button className={`answer-card ${choice===side ? "selected" : ""}`} key={side} disabled={Boolean(choice)} onClick={event=>handleChoose(side,event.timeStamp)} aria-pressed={choice===side}><span className="answer-label">{i===0 ? "A" : "B"}<span>Answer {i===0 ? "A" : "B"}</span>{choice===side && <Check size={18} aria-label="Selected" />}</span><span className="answer-text">{"left" in item.display ? item.display[side] : ""}</span><span className="answer-bottom">This one has the lie <ArrowRight size={16} aria-hidden="true" /></span></button>)}</div>}{choice && !reveal && <section className="confidence panel" aria-labelledby="confidence-title"><h2 id="confidence-title">How confident are you?</h2><p className="muted">Trust your gut. There’s no wrong confidence level.</p><div className="confidence-buttons">{[1,2,3,4,5].map(n=><button key={n} disabled={sending} onClick={()=>void submit(n)} aria-label={`${n}${n===1 ? " Pure guess" : n===5 ? " Certain" : ""}`}>{n}</button>)}</div><div className="confidence-scale"><span>Pure guess</span><span>Certain</span></div>{sending && <p role="status">Recording your guess…</p>}</section>}{error && <p role="alert" className="error">{error}</p>}<div aria-live="polite" aria-atomic="true">{reveal && <section className={`reveal panel ${reveal.isCorrect ? "correct" : "incorrect"}`}><h2>{reveal.isCorrect ? <CheckCircle2 aria-hidden="true" /> : <XCircle aria-hidden="true" />}{reveal.isCorrect ? "Caught it!" : "That one slipped through."}</h2><p className="eyebrow">The fabricated answer · {reveal.wasFabricated === "left" ? "A" : "B"}</p><p className="fabricated">{index >= 0 ? <>{reveal.fabricatedAnswer.slice(0,index)}<mark>{reveal.fabricatedSpan}</mark>{reveal.fabricatedAnswer.slice(index + reveal.fabricatedSpan.length)}</> : reveal.fabricatedAnswer}</p><p>{reveal.explanation}</p>{reveal.sourceUrl && <a className="source" href={reveal.sourceUrl} target="_blank" rel="noopener noreferrer">Check the source ↗</a>}<div className="reveal-bottom"><span className="muted">{reveal.score} correct so far</span><button className="button primary" onClick={()=>void next()} disabled={busy}>{busy ? "Loading…" : item.position===item.totalItems ? "See results" : "Next"}<ArrowRight aria-hidden="true" /></button></div></section>}</div></section>;
}
